# Generated by Django 4.2.1 on 2023-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='content',
            field=models.TextField(default='', max_length=8000, unique=True),
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
