# Generated by Django 4.2.1 on 2023-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogsmodel_date_alter_blogsmodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
