# Generated by Django 4.2.1 on 2023-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='date',
            field=models.DateTimeField(default='2005-12-05 22:22:44:000000'),
        ),
    ]
